export const DEFAULT_CONFIG = {
    LOGGING: false,
    MAX_TOKEN_SIZE: 500,
    SIMILARITY_THRESHOLD: 0.7,
    DYNAMIC_THRESHOLD_LOWER_BOUND: 0.55,
    DYNAMIC_THRESHOLD_UPPER_BOUND: 0.85,
    NUM_SIMILARITY_SENTENCES_LOOKAHEAD: 3,
    COMBINE_CHUNKS: true,
    COMBINE_CHUNKS_SIMILARITY_THRESHOLD: 0.7,
    RETURN_EMBEDDING: false,
    RETURN_TOKEN_LENGTH: true,
    CHUNK_PREFIX: null,
    EXCLUDE_CHUNK_PREFIX_IN_RESULTS: false,
};